<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Version>0.1.0</Version>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup>
		<Authors>filipw;qsharp-community</Authors>
	</PropertyGroup>

	<ItemGroup>
		<None Condition="$([MSBuild]::IsOsPlatform('Linux'))" Include="libqsharp_bridge.so" CopyToOutputDirectory="PreserveNewest" />
		<None Condition="$([MSBuild]::IsOsPlatform('Windows'))" Include="qsharp_bridge.dll" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>